#!/bin/bash
# Remove the duplicate user block before Cart
sed -i '272,278d' src/Store.tsx

# Replace dropdown links with working ones
sed -i 's/<button className={`w-full text-left px-5 py-2.5 text-sm transition-colors ${isDarkMode ? '"'"'hover:bg-blue-500\/10 hover:text-blue-400'"'"' : '"'"'hover:bg-blue-50 hover:text-blue-600'"'"'}`}>My Profile<\/button>/<button onClick={() => { setIsProfileMenuOpen(false); navigate('"'"'\/profile'"'"'); }} className={`w-full text-left px-5 py-2.5 text-sm transition-colors ${isDarkMode ? '"'"'hover:bg-blue-500\/10 hover:text-blue-400'"'"' : '"'"'hover:bg-blue-50 hover:text-blue-600'"'"'}`}>My Profile<\/button>/g' src/Store.tsx
sed -i 's/<button className={`w-full text-left px-5 py-2.5 text-sm transition-colors ${isDarkMode ? '"'"'hover:bg-blue-500\/10 hover:text-blue-400'"'"' : '"'"'hover:bg-blue-50 hover:text-blue-600'"'"'}`}>My Orders<\/button>/<button onClick={() => { setIsProfileMenuOpen(false); navigate('"'"'\/profile'"'"'); }} className={`w-full text-left px-5 py-2.5 text-sm transition-colors ${isDarkMode ? '"'"'hover:bg-blue-500\/10 hover:text-blue-400'"'"' : '"'"'hover:bg-blue-50 hover:text-blue-600'"'"'}`}>My Orders<\/button>/g' src/Store.tsx
sed -i 's/<button className={`w-full text-left px-5 py-2.5 text-sm transition-colors ${isDarkMode ? '"'"'hover:bg-blue-500\/10 hover:text-blue-400'"'"' : '"'"'hover:bg-blue-50 hover:text-blue-600'"'"'}`}>Saved\/Favorites<\/button>/<button onClick={() => { setIsProfileMenuOpen(false); navigate('"'"'\/profile'"'"'); }} className={`w-full text-left px-5 py-2.5 text-sm transition-colors ${isDarkMode ? '"'"'hover:bg-blue-500\/10 hover:text-blue-400'"'"' : '"'"'hover:bg-blue-50 hover:text-blue-600'"'"'}`}>Saved\/Favorites<\/button>/g' src/Store.tsx
sed -i 's/<button className={`w-full text-left px-5 py-2.5 text-sm transition-colors ${isDarkMode ? '"'"'hover:bg-blue-500\/10 hover:text-blue-400'"'"' : '"'"'hover:bg-blue-50 hover:text-blue-600'"'"'}`}>Settings<\/button>/<button onClick={() => { setIsProfileMenuOpen(false); navigate('"'"'\/profile'"'"'); }} className={`w-full text-left px-5 py-2.5 text-sm transition-colors ${isDarkMode ? '"'"'hover:bg-blue-500\/10 hover:text-blue-400'"'"' : '"'"'hover:bg-blue-50 hover:text-blue-600'"'"'}`}>Settings<\/button>\n                        {user.email === '"'"'damijosh12@gmail.com'"'"' \&\& <button onClick={() => { setIsProfileMenuOpen(false); navigate('"'"'\/admin'"'"'); }} className={`w-full text-left px-5 py-2.5 text-sm transition-colors ${isDarkMode ? '"'"'hover:bg-purple-500\/10 hover:text-purple-400 text-purple-400'"'"' : '"'"'hover:bg-purple-50 hover:text-purple-600 text-purple-600'"'"'}`}>Admin Dashboard<\/button>}/g' src/Store.tsx

# Also fix mobile bottom nav so it doesn't have duplicate profile routes. Let's make the second one go to a different active state or just remove the 'orders' one.
sed -i 's/activeMobileTab === '"'"'orders'"'"'/activeMobileTab === '"'"'orders_tab'"'"'/g' src/Store.tsx
